# Generated by Django 4.2.9 on 2024-01-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_category_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='assignment',
            field=models.ManyToManyField(related_name='category', to='accounts.assignment'),
        ),
    ]
