# Generated by Django 4.2.9 on 2024-01-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_assignment_category_myclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='myclass',
            field=models.ManyToManyField(related_name='categories_in_category', to='accounts.myclass'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='categories',
            field=models.ManyToManyField(related_name='classes_in_myclass', to='accounts.category'),
        ),
    ]
